modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="waterlands"
version="1.0.0"
displayName="WaterLands"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="jwzwi, MCreator"

[[dependencies.waterlands]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




